# playbook.yml
---
- name: Deploying CalcDevOps
  hosts: localhost
  connection: local
  tasks:
    - name: pull an image
      docker_image:
        name: rohitkatlaa/calc_dev_ops:latest

    - name: Creation of Docker Containers
      docker_container:
        name: calc-{{ item }}
        image: rohitkatlaa/calc_dev_ops:latest
        state: present
      with_sequence: count=3

    - name: Starting Docker Containers
      docker_container:
        name: calc-{{ item }}
        image: rohitkatlaa/calc_dev_ops:latest
        state: started
      with_sequence: count=3