# playbook.yml
---
- name: Deploying CalcDevOps
  # hosts: all
  hosts: localhost
  connection: local
  remote_user: rohit
  tasks:
    - name: pull an image
      docker_image:
        name: rohitkatlaa/calc_dev_ops:latest